// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6y7B74PT4qsYm11gv7_cmpr6v83w9CDI',
    appId: '1:68775835086:web:81b93a6e7ffde894b7a79f',
    messagingSenderId: '68775835086',
    projectId: 'movies-app-ff74e',
    authDomain: 'movies-app-ff74e.firebaseapp.com',
    storageBucket: 'movies-app-ff74e.appspot.com',
    measurementId: 'G-WYE3479MW9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUDT13-NEqzmnNOvGwtoljmr4vBKb8B-A',
    appId: '1:68775835086:android:f8da294112440ad1b7a79f',
    messagingSenderId: '68775835086',
    projectId: 'movies-app-ff74e',
    storageBucket: 'movies-app-ff74e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnmf6F0CFhDO5J8Em8caHFO906OEzhq_g',
    appId: '1:68775835086:ios:fb1fbf13320a8e03b7a79f',
    messagingSenderId: '68775835086',
    projectId: 'movies-app-ff74e',
    storageBucket: 'movies-app-ff74e.appspot.com',
    iosClientId: '68775835086-uk9ns4anq8fhidi2aq3ugt304cf509es.apps.googleusercontent.com',
    iosBundleId: 'com.example.moviesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnmf6F0CFhDO5J8Em8caHFO906OEzhq_g',
    appId: '1:68775835086:ios:fb1fbf13320a8e03b7a79f',
    messagingSenderId: '68775835086',
    projectId: 'movies-app-ff74e',
    storageBucket: 'movies-app-ff74e.appspot.com',
    iosClientId: '68775835086-uk9ns4anq8fhidi2aq3ugt304cf509es.apps.googleusercontent.com',
    iosBundleId: 'com.example.moviesApp',
  );
}
